baseURL = "http://viaphoniker.eu"
languageCode = "de-de"
enableGitInfo = true
title = "ViaphonikerInnen"
[markup.goldmark.renderer]
unsafe = true
[params]
custom_css = ["css/menu.css", "css/style.css"]
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

