baseURL = 'http://viaphoniker.eu/'
languageCode = 'de-de'
title = 'ViaphonikerInnen'

[markup.goldmark.renderer]
unsafe = true

[params]
custom_css = ["css/menu.css", "css/style.css"]


[menu]
  [[menu.main]]
  name = 'Google'
  url = 'http://www.google.de'
  weight = 100