baseURL = "https://gracious-ardinghelli-66b164.netlify.app/"
languageCode = "de-de"
title = "ViaphonikerInnen"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Retrospektive"
weight = 6
[params]
custom_css = ["css/menu.css", "css/style.css"]
